autoplayer_ann_mode = b1_path_grading_hack
autoplayer_ann_layers = {{count = 4, activation_function_name = "identity"}, {count = 3, activation_function_name = "tanh"}, {count = 1, activation_function_name = "binary_step"}}
