autoplayer_ann_mode = nb4_path_grading
autoplayer_ann_layers = {{count = 4, activation_function_name = "identity"}, {count = 3, activation_function_name = "relu"}, {count = 3, activation_function_name = "relu"}, {count = 1, activation_function_name = "identity"}}
